### PR TITLE
Import security updates from Ubuntu 16.04 up to 2.4-0ubuntu6.6

### PR DESCRIPTION
**Pull request by peat-psuwit**
This PR brings in security updates for WPA packages. Multiple vulnerabilities are fixed.

Marius has already brought in `debian/patches/2017-1/*.patch`, however, one patch seems to be left out of the series. This may indicate that the patch introduces a regression. Also, the amount of patches is significant and we have a few custom patches of our own. Thus, thorough testing is needed.

This PR also comes with  Jenkinsfile update.

This is a potential candidate for inclusion in OTA-12.

### CODE REVIEW

**Comment by peat-psuwit** [comment]
This has been tested on bq Aquaris E4.5, bq Aquaris M10 FHD, and Meizu MX4. The devices seem to be able to connect to my network using WPA2-PSK. Additionally, my M10 FHD seems to be able to search & connect to my Miracast-compatible TV, to an extent (it can't actually mirror the display: it never works with this TV).

So, this is probably ready to be more widely tested. @UniversalSuperBox, please add the list of supported devices to be tested.

**Comment by UniversalSuperBox** [comment]
We must receive a test from every supported device for this to be merged. WiFi hardware must be tested for its functionality equal to before this change is installed.

If you can, please test connecting to a WPA-Enterprise network and/or a Miracast adapter (not necessarily at the same time though).

We'd like these tests on devel.

* [x] Meizu MX4
* [x] Oneplus One
* [x] Fairphone 2
* [x] Nexus 5
* [x] BQ M10 FHD
* [ ] BQ M10 HD
* [x] BQ E4.5
* [ ] BQ E5
* [x] Meizu Pro 5
* [ ] Nexus 4
* [x] Nexus 7 2013 WiFi
* [ ] Nexus 7 2013 LTE
* [ ] Moto G 2014 (@walidham)
* [ ] OnePlus 3
* [ ] OnePlus 3T
* [x] Xperia X

**Comment by peat-psuwit** [comment]
So, I decided to set up my personal WPA-EAP access point using hostapd [1]. Using my M10 FHD, it seems to work fine with both EAP-PEAP with MSCHAPv2 and EAP-TTLS with EAP-PAP.

[1] Did you know that hostapd has a built-in RADIUS server?

**Review by UniversalSuperBox — APPROVED** [review]
Given multiple calls for testing have been sent and not responded to, and we seem to have covered each major platform of WLAN hardware, I feel it is safe to merge this for OTA-12.

**Comment by j2g2rp** [comment]
Not sure how to test this but Nexus 5 and BQM10FHD are working fine connected to a WPA + WPA2 network

**Comment by abkro** [comment]
Nexus 5 hammerhead, RC 2020-W16. Everything good, both on home network (WPA2) and enterprise network (WPA2 Enterprise).

**Comment by Bolly** [comment]
Checked this on a BQM10FHD running RC 2020 W-18, W-17, W-16 & W-15.
It works on WPA2.

**Comment by megahirtz** [comment]
OnePlus One running RC. Works on WPA2.

**Comment by Sonkei** [comment]
BQ E5 running RC. Works on WPA2-personnel.

**Comment by Bolly** [comment]
Checked this on a BQE4.5 running RC 2020 W-18. 
It works on WPA2.

**Pull request merged**
